email.enabled=true
email.host=smtp.gmail.com
email.portnumber=587
email.username=YOUR_EMAIL_USERNAME
email.password=YOUR_EMAIL_PASSWORD
email.senderName=vastu
email.senderEmail=admin@vastu.com
email.replyTo=no-reply@vastu.com
