sms.enabled=true
sms.sender=smsgupshup
sms.twilio.accountsid=YOUR_TWILIO_ACCOUNT_SID
sms.twilio.authtoken=YOUR_TWILIO_AUTH_TOKEN
sms.twilio.phonenumber=YOUR_TWILIO_PHONE_NUMBER
sms.smsgupshup.userid=YOUR_SMS_GUPSHUP_USER_ID
sms.smsgupshup.password=YOUR_SMS_GUPSHUP_PASSWORD
